export type DistrictWithArea = {
    [key: string]: string[];
};

export const districts = [
    {
        value: "Bagerhat",
        label: "Bagerhat",
    },
    {
        value: "Bandarban",
        label: "Bandarban",
    },
    {
        value: "Barguna",
        label: "Barguna",
    },
    {
        value: "Barisal",
        label: "Barisal",
    },
    {
        value: "Bhola",
        label: "Bhola",
    },
    {
        value: "Bogra",
        label: "Bogra",
    },
    {
        value: "Brahmanbaria",
        label: "Brahmanbaria",
    },
    {
        value: "Chandpur",
        label: "Chandpur",
    },
    {
        value: "Chapai Nawabganj",
        label: "Chapai Nawabganj",
    },
    {
        value: "Chattogram",
        label: "Chattogram",
    },
    {
        value: "Chuadanga",
        label: "Chuadanga",
    },
    {
        value: "Cox's Bazar",
        label: "Cox's Bazar",
    },
    {
        value: "Cumilla",
        label: "Cumilla",
    },
    {
        value: "Dhaka",
        label: "Dhaka",
    },
    {
        value: "Dinajpur",
        label: "Dinajpur",
    },
    {
        value: "Faridpur",
        label: "Faridpur",
    },
    {
        value: "Feni",
        label: "Feni",
    },
    {
        value: "Gaibandha",
        label: "Gaibandha",
    },
    {
        value: "Gazipur",
        label: "Gazipur",
    },
    {
        value: "Gopalganj",
        label: "Gopalganj",
    },
    {
        value: "Habiganj",
        label: "Habiganj",
    },
    {
        value: "Jamalpur",
        label: "Jamalpur",
    },
    {
        value: "Jashore",
        label: "Jashore",
    },
    {
        value: "Jhalokati",
        label: "Jhalokati",
    },
    {
        value: "Jhenaidah",
        label: "Jhenaidah",
    },
    {
        value: "Joypurhat",
        label: "Joypurhat",
    },
    {
        value: "Khagrachari",
        label: "Khagrachari",
    },
    {
        value: "Khulna",
        label: "Khulna",
    },
    {
        value: "Kishoreganj",
        label: "Kishoreganj",
    },
    {
        value: "Kurigram",
        label: "Kurigram",
    },
    {
        value: "Kushtia",
        label: "Kushtia",
    },
    {
        value: "Lakshmipur",
        label: "Lakshmipur",
    },
    {
        value: "Lalmonirhat",
        label: "Lalmonirhat",
    },
    {
        value: "Madaripur",
        label: "Madaripur",
    },
    {
        value: "Magura",
        label: "Magura",
    },
    {
        value: "Manikganj",
        label: "Manikganj",
    },
    {
        value: "Meherpur",
        label: "Meherpur",
    },
    {
        value: "Moulvibazar",
        label: "Moulvibazar",
    },
    {
        value: "Munshiganj",
        label: "Munshiganj",
    },
    {
        value: "Mymensingh",
        label: "Mymensingh",
    },
    {
        value: "Naogaon",
        label: "Naogaon",
    },
    {
        value: "Narail",
        label: "Narail",
    },
    {
        value: "Narayanganj",
        label: "Narayanganj",
    },
    {
        value: "Narsingdi",
        label: "Narsingdi",
    },
    {
        value: "Natore",
        label: "Natore",
    },
    {
        value: "Netrokona",
        label: "Netrokona",
    },
    {
        value: "Nilphamari",
        label: "Nilphamari",
    },
    {
        value: "Noakhali",
        label: "Noakhali",
    },
    {
        value: "Pabna",
        label: "Pabna",
    },
    {
        value: "Panchagarh",
        label: "Panchagarh",
    },
    {
        value: "Patuakhali",
        label: "Patuakhali",
    },
    {
        value: "Pirojpur",
        label: "Pirojpur",
    },
    {
        value: "Rajbari",
        label: "Rajbari",
    },
    {
        value: "Rajshahi",
        label: "Rajshahi",
    },
    {
        value: "Rangamati",
        label: "Rangamati",
    },
    {
        value: "Rangpur",
        label: "Rangpur",
    },
    {
        value: "Satkhira",
        label: "Satkhira",
    },
    {
        value: "Shariatpur",
        label: "Shariatpur",
    },
    {
        value: "Sherpur",
        label: "Sherpur",
    },
    {
        value: "Sirajganj",
        label: "Sirajganj",
    },
    {
        value: "Sunamganj",
        label: "Sunamganj",
    },
    {
        value: "Sylhet",
        label: "Sylhet",
    },
    {
        value: "Tangail",
        label: "Tangail",
    },
    {
        value: "Thakurgaon",
        label: "Thakurgaon",
    },
];

export const districtsWithSubAreas: DistrictWithArea = {
    Bagerhat: [
        "Bagerhat Sadar",
        "Chitalmari",
        "Fakirhat",
        "Kachua",
        "Mollahat",
        "Mongla",
        "Morrelganj",
        "Rampal",
        "Sarankhola",
    ],
    Bandarban: [
        "Bandarban Sadar",
        "Thanchi",
        "Ruma",
        "Rowangchhari",
        "Lama",
        "Alikadam",
        "Naikhongchhari",
    ],
    Barguna: [
        "Amtali",
        "Barguna Sadar",
        "Betagi",
        "Bamna",
        "Patharghata",
        "Taltali",
    ],
    Barisal: [
        "Barisal Sadar",
        "Bakerganj",
        "Babuganj",
        "Banaripara",
        "Gournadi",
        "Hizla",
        "Mehendiganj",
        "Muladi",
        "Wazirpur",
    ],
    Bhola: [
        "Bhola Sadar",
        "Borhanuddin",
        "Char Fasson",
        "Daulatkhan",
        "Lalmohan",
        "Monpura",
        "Tazumuddin",
    ],
    Bogra: [
        "Adamdighi",
        "Bogra Sadar",
        "Dhunat",
        "Dupchanchia",
        "Gabtali",
        "Kahaloo",
        "Nandigram",
        "Sariakandi",
        "Sherpur",
        "Shibganj",
        "Sonatala",
    ],
    Brahmanbaria: [
        "Brahmanbaria Sadar",
        "Ashuganj",
        "Bancharampur",
        "Bijoynagar",
        "Kasba",
        "Nabinagar",
        "Nasirnagar",
        "Sarail",
    ],
    Chandpur: [
        "Chandpur Sadar",
        "Faridganj",
        "Haimchar",
        "Haziganj",
        "Kachua",
        "Matlab North",
        "Matlab South",
    ],
    ChapaiNawabganj: [
        "Chapai Nawabganj Sadar",
        "Bholahat",
        "Gomostapur",
        "Nachole",
        "Shibganj",
    ],
    Chattogram: [
        "Chattogram Sadar",
        "Anwara",
        "Banshkhali",
        "Boalkhali",
        "Fatikchhari",
        "Hathazari",
        "Lohagara",
        "Mirsharai",
        "Patiya",
        "Rangunia",
        "Raozan",
        "Sandwip",
        "Satkania",
        "Sitakunda",
    ],
    Chuadanga: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
    CoxsBazar: [
        "Chakaria",
        "Cox's Bazar Sadar",
        "Kutubdia",
        "Maheshkhali",
        "Pekua",
        "Ramu",
        "Teknaf",
        "Ukhiya",
    ],
    Cumilla: [
        "Cumilla Sadar",
        "Cumilla Sadar South",
        "Barura",
        "Brahmanpara",
        "Burichang",
        "Chandina",
        "Daudkandi",
        "Debidwar",
        "Homna",
        "Laksam",
        "Meghna",
        "Monohorgonj",
        "Muradnagar",
        "Titas",
    ],
    Dhaka: [
        "Dhanmondi",
        "Gulshan",
        "Mirpur",
        "Uttara",
        "Mohammadpur",
        "Tejgaon",
        "Pallabi",
        "Shahbagh",
        "Jatrabari",
        "Sutrapur",
        "Kamrangirchar",
    ],
    Dinajpur: [
        "Birampur",
        "Birganj",
        "Biral",
        "Bochaganj",
        "Chirirbandar",
        "Dinajpur Sadar",
        "Ghoraghat",
        "Hakimpur",
        "Kaharole",
        "Khansama",
        "Nawabganj",
        "Parbatipur",
    ],
    Faridpur: [
        "Faridpur Sadar",
        "Alfadanga",
        "Bhanga",
        "Boalmari",
        "Charbhadrasan",
        "Madhukhali",
        "Nagarkanda",
        "Sadarpur",
        "Saltha",
    ],
    Feni: [
        "Chhagalnaiya",
        "Daganbhuiyan",
        "Feni Sadar",
        "Fulgazi",
        "Parshuram",
        "Sonagazi",
    ],
    Gaibandha: [
        "Fulchhari",
        "Gaibandha Sadar",
        "Gobindaganj",
        "Palashbari",
        "Sadullapur",
        "Saghata",
        "Sundarganj",
    ],
    Gazipur: [
        "Gazipur Sadar",
        "Kaliganj",
        "Kaliganj",
        "Kapasia",
        "Sreepur",
        "Tongi",
    ],
    Gopalganj: [
        "Gopalganj Sadar",
        "Kashiani",
        "Kotalipara",
        "Muksudpur",
        "Tungipara",
    ],
    Habiganj: [
        "Ajmiriganj",
        "Bahubal",
        "Baniachong",
        "Chunarughat",
        "Habiganj Sadar",
        "Lakhai",
        "Madhabpur",
        "Nabiganj",
    ],
    Jamalpur: [
        "Baksiganj",
        "Dewanganj",
        "Islampur",
        "Jamalpur Sadar",
        "Madarganj",
        "Melandaha",
        "Sarishabari",
    ],
    Jashore: [
        "Abhaynagar",
        "Bagherpara",
        "Chaugachha",
        "Jashore Sadar",
        "Jhikargachha",
        "Keshabpur",
        "Manirampur",
        "Sharsha",
    ],
    Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
    Jhenaidah: [
        "Harinakunda",
        "Jhenaidah Sadar",
        "Kaliganj",
        "Kotchandpur",
        "Maheshpur",
        "Shailkupa",
    ],
    Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
    Khagrachari: [
        "Dighinala",
        "Khagrachari Sadar",
        "Lakshmichhari",
        "Mahalchhari",
        "Manikchhari",
        "Matiranga",
        "Panchhari",
        "Ramgarh",
    ],
    Khulna: [
        "Batiaghata",
        "Dacope",
        "Dumuria",
        "Dighalia",
        "Khalishpur",
        "Koyra",
        "Paikgachha",
        "Phultala",
        "Rupsa",
        "Terokhada",
    ],
    Kishoreganj: [
        "Austagram",
        "Bajitpur",
        "Bhairab",
        "Hossainpur",
        "Itna",
        "Karimganj",
        "Katiadi",
        "Kishoreganj Sadar",
        "Kuliarchar",
        "Mithamain",
        "Nikli",
        "Pakundia",
        "Tarail",
    ],
    Kurigram: [
        "Bhurungamari",
        "Chilmari",
        "Kurigram Sadar",
        "Nageshwari",
        "Phulbari",
        "Rajarhat",
        "Rajibpur",
        "Rowmari",
        "Ulipur",
    ],
    Kushtia: [
        "Bheramara",
        "Daulatpur",
        "Khoksa",
        "Kumarkhali",
        "Kushtia Sadar",
        "Mirpur",
    ],
    Lakshmipur: [
        "Lakshmipur Sadar",
        "Raipur",
        "Ramganj",
        "Ramgati",
        "Kamalnagar",
    ],
    Lalmonirhat: [
        "Aditmari",
        "Hatibandha",
        "Kaliganj",
        "Lalmonirhat Sadar",
        "Patgram",
    ],
    Madaripur: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
    Manikganj: [
        "Daulatpur",
        "Ghior",
        "Harirampur",
        "Manikganj Sadar",
        "Saturia",
        "Shibalaya",
        "Singair",
    ],
    Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
    Moulvibazar: [
        "Barlekha",
        "Juri",
        "Kamalganj",
        "Kulaura",
        "Moulvibazar Sadar",
        "Rajnagar",
        "Sreemangal",
    ],
    Munshiganj: [
        "Gazaria",
        "Lohajang",
        "Munshiganj Sadar",
        "Sirajdikhan",
        "Sreenagar",
        "Tongibari",
    ],
    Mymensingh: [
        "Bhaluka",
        "Dhobaura",
        "Fulbaria",
        "Gaffargaon",
        "Gauripur",
        "Haluaghat",
        "Ishwarganj",
        "Mymensingh Sadar",
        "Muktagachha",
        "Nandail",
        "Phulpur",
        "Trishal",
    ],

    Naogaon: [
        "Atrai",
        "Badalgachhi",
        "Dhamoirhat",
        "Manda",
        "Mahadevpur",
        "Naogaon Sadar",
        "Niamatpur",
        "Patnitala",
        "Porsha",
        "Raninagar",
        "Sapahar",
    ],
    Narail: ["Kalia", "Lohagara", "Narail Sadar"],
    Narayanganj: [
        "Araihazar",
        "Bandar",
        "Narayanganj Sadar",
        "Rupganj",
        "Sonargaon",
    ],
    Narsingdi: [
        "Belabo",
        "Monohardi",
        "Narsingdi Sadar",
        "Palash",
        "Raipura",
        "Shibpur",
    ],
    Natore: [
        "Bagatipara",
        "Baraigram",
        "Gurudaspur",
        "Lalpur",
        "Natore Sadar",
        "Singra",
    ],
    Netrokona: [
        "Atpara",
        "Barhatta",
        "Durgapur",
        "Kendua",
        "Kalmakanda",
        "Madan",
        "Mohanganj",
        "Netrokona Sadar",
        "Purbadhala",
    ],
    Nilphamari: [
        "Dimla",
        "Domar",
        "Jaldhaka",
        "Kishoreganj",
        "Nilphamari Sadar",
        "Saidpur",
    ],
    Noakhali: [
        "Begumganj",
        "Chatkhil",
        "Companiganj",
        "Hatiya",
        "Noakhali Sadar",
        "Senbagh",
        "Subarnachar",
    ],
    Pabna: [
        "Atgharia",
        "Bera",
        "Bhangura",
        "Chatmohar",
        "Faridpur",
        "Ishwardi",
        "Pabna Sadar",
        "Santhia",
        "Sujanagar",
    ],
    Panchagarh: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
    Patuakhali: [
        "Bauphal",
        "Dashmina",
        "Galachipa",
        "Kalapara",
        "Mirzaganj",
        "Patuakhali Sadar",
        "Rangabali",
    ],
    Pirojpur: [
        "Bhandaria",
        "Kawkhali",
        "Mathbaria",
        "Nazirpur",
        "Nesarabad (Swarupkathi)",
        "Pirojpur Sadar",
        "Zianagar (Indurkani)",
    ],
    Rajbari: [
        "Baliakandi",
        "Goalandaghat",
        "Pangsha",
        "Rajbari Sadar",
        "Kalukhali",
    ],
    Rajshahi: [
        "Bagha",
        "Bagmara",
        "Charghat",
        "Durgapur",
        "Godagari",
        "Mohanpur",
        "Paba",
        "Puthia",
        "Tanore",
    ],
    Rangamati: [
        "Baghaichhari",
        "Barkal",
        "Belaichhari",
        "Juraichhari",
        "Kaptai",
        "Langadu",
        "Naniarchar",
        "Rajasthali",
        "Rangamati Sadar",
    ],
    Rangpur: [
        "Badarganj",
        "Gangachhara",
        "Kaunia",
        "Mithapukur",
        "Pirgachha",
        "Pirgasa",
        "Rangpur Sadar",
        "Taraganj",
    ],
    Satkhira: [
        "Assasuni",
        "Debhata",
        "Kaliganj",
        "Kalaroa",
        "Satkhira Sadar",
        "Shyamnagar",
        "Tala",
    ],
    Shariatpur: [
        "Bhedarganj",
        "Damudya",
        "Gosairhat",
        "Naria",
        "Shariatpur Sadar",
        "Zajira",
    ],
    Sherpur: [
        "Jhenaigati",
        "Nakla",
        "Nalitabari",
        "Sherpur Sadar",
        "Sreebardi",
    ],
    Sirajganj: [
        "Belkuchi",
        "Chauhali",
        "Kamarkhanda",
        "Kazipur",
        "Raiganj",
        "Shahjadpur",
        "Sirajganj Sadar",
        "Tarash",
        "Ullahpara",
    ],
    Sunamganj: [
        "Bishwamvarpur",
        "Chhatak",
        "Dharampasha",
        "Dowarabazar",
        "Jagannathpur",
        "Jamalganj",
        "Sullah",
        "Sunamganj Sadar",
        "Tahirpur",
    ],
    Sylhet: [
        "Balaganj",
        "Beanibazar",
        "Bishwanath",
        "Companiganj",
        "Dakshin Surma",
        "Fenchuganj",
        "Golapganj",
        "Gowainghat",
        "Jaintiapur",
        "Kanaighat",
        "Sylhet Sadar",
        "Zakiganj",
    ],
    Tangail: [
        "Bhuapur",
        "Delduar",
        "Dhanbari",
        "Ghatail",
        "Gopalpur",
        "Kalihati",
        "Madhupur",
        "Mirzapur",
        "Nagarpur",
        "Sakhipur",
        "Tangail Sadar",
        "Basail",
    ],
    Thakurgaon: [
        "Baliadangi",
        "Haripur",
        "Pirganj",
        "Ranisankail",
        "Thakurgaon Sadar",
    ],
};
